org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
fabric_version=0.116.6+1.21.1

mod_version=1.0.0
maven_group=com.jimmykolev
archives_base_name=donutsmp-sellall
